-- MySQL Script generated by MySQL Workbench
-- Tue Jan 31 17:07:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema provas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `provas` ;

-- -----------------------------------------------------
-- Schema provas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `provas` DEFAULT CHARACTER SET latin1 ;
USE `provas` ;

DROP USER `sisprovas`@`localhost`;
CREATE USER `sisprovas`@`localhost` identified by "123456";
GRANT ALL PRIVILEGES ON provas.* TO `sisprovas`@`localhost`;
FLUSH PRIVILEGES;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
